### ISSUE TITLE
Implementing PostgreSQL

### ISSUE THREAD

**Issue by Skibooss** [aenima-x/BlackHole#10]
HI,
Very good solution, thx for sharing. :D
I'm just a little bt disapointing that Postgres is not implmenting. :/

Maybe I should try to implement that. ^^

**Comment by aenima-x** [comment]
You are right I will add support for Postgres

**Comment by aenima-x** [comment]
I think its not gonna be possibe. Because the psql command don't accept the password as parameter.
The only workaround I found was to execute it like this:
export PGPASSWORD='XXXX' && psql -d DATABASE -h x.x.x.x  -U USER

But that doesn't work with the way that blackhole spawn the command to capture te output

**Comment by aenima-x** [comment]
You could write a shell script that run that line, and set it as the postgres command.
But it's an ugly hack and I don't want to add it

**Comment by aenima-x** [comment]
Ready, It has support for PostgreSQL

**Comment by Skibooss** [comment]
Thx a lot ! :)
